name: Postman Teste reqres Api

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Step 1 Check version Newman and Node
        run: |
          newman --version
          node --version

      - name: Step 2 Install Newman-Reporter-Htmlextra
        run: sudo npm install -g newman-reporter-htmlextra

      - name: Step 3 Execute collection
        run: newman run ./reqres-api.json --reporters cli,htmlextra --reporter-htmlextra-export ./results/Report.html

      - name: Step 4 Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: ./results/Report.html

      - name: Create Report Link Comment
        run: |
          const fs = require('fs');
          const { Octokit } = require('@octokit/rest');
          
          const reportPath = './results/Report.html';
          const reportURL = `https://github.com/${process.env.GITHUB_REPOSITORY}/blob/${process.env.GITHUB_SHA}/${reportPath}`;
          
          const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });
          octokit.rest.issues.createComment({
            owner: process.env.GITHUB_REPOSITORY_OWNER,
            repo: process.env.GITHUB_REPOSITORY_NAME,
            issue_number: process.env.GITHUB_ISSUE_NUMBER,
            body: `The test report is available [here](${reportURL}).`
          });

