name: Postman Teste reqres Api

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Step 1 Check version Newman and Node
        run: |
          newman --version
          node --version

      - name: Step 2 Install Newman-Reporter-HTML
        run: npm install -g newman-reporter-html

      - name: Step 3 Execute collection
        run: newman run ./reqres-api.json -r html --reporter-html-export ./newman-report.html

      - name: Step 4 Archive Newman report
        uses: actions/upload-artifact@v2
        with:
          name: newman-report
          path: ./newman-report.html

      - name: Validate links
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@master
          - name: Validate links
            uses: ad-m/report-link-action@master
            with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
