name: Postman Teste reqres Api

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Step 1 Check version Newman and Node
        run: |
          newman --version
          node --version

      - name: Step 2 Install Newman-Reporter-Htmlextra
        run: sudo npm install -g newman-reporter-htmlextra

      - name: Step 3 Execute collection
        run: newman run ./reqres-api.json --reporters cli, -r htmlextra --reporter-htmlextra-export ./results/Report.html

      - name: Step 4 Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: ./results/Report.html

      - name: Step 5 Generate Report Link
        id: report-link
        run: |
          echo "::set-output name=report_path::$(realpath ./results/Report.html)"

- name: Step 6 Create Report Link Comment
  uses: actions/github-script@v4
  with:
    github-token: ${{ secrets.GITHUB_TOKEN }}
    script: |
      const reportPath = "${{ steps.report-link.outputs.report_path }}";
      const reportURL = `https://github.com/${{ github.repository }}/blob/${{ github.sha }}/${reportPath}`;
      const context = github.context;
      const octokit = github.getOctokit(process.env.GITHUB_TOKEN);
      
      octokit.issues.createComment({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        body: `The test report is available [here](${reportURL}).`
      });

