name: Postman Tests with Allure Report

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Newman and Allure Command Line
        run: |
          npm install -g newman
          npm install -g allure-commandline

      - name: Execute Postman collection
        run: newman run ./reqres-api.json --reporters cli,junit --reporter-junit-export ./newman-results.xml

      - name: Generate Allure Report
        run: allure generate -c -o ./allure-report

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Build and Deploy to GitHub Pages
        run: |
          npm install -g allure-commandline
          allure generate allure-results --clean -o allure-report
          echo '<meta http-equiv="refresh" content="0;url=allure-report/index.html">' > allure-report/index.html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
