name: Postman Teste reqres Api

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Step 1 Check version Newman and Node
        run: |
          newman --version
          node --version

      - name: Step 2 Install Newman-Reporter-Htmlextra
        run: sudo npm install -g newman-reporter-htmlextra

      - name: Step 3 Execute collection
        run: newman run ./reqres-api.json --reporters cli -r htmlextra --reporter-htmlextra-export ./results/Report.html

      - name: Step 4 Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: ./results/Report.html

      - name: Step 5 Generate Report Link
        id: report-link
        run: |
          echo "REPORT_PATH=$(realpath ./results/Report.html)" >> $GITHUB_ENV

      - name: Install @actions/github
        run: npm install @actions/github

      - name: Step 6 Create Report Link Comment
        run: |
          const { getOctokit, context } = require('@actions/github');
          const reportPath = process.env.REPORT_PATH;
          const reportURL = `https://github.com/${context.repo.owner}/${context.repo.repo}/blob/${context.sha}${reportPath}`;
          const octokit = getOctokit(process.env.GITHUB_TOKEN);

          octokit.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.payload.issue.number,
            body: `The test report is available [here](${reportURL}).`
          });
