name: Postman Teste reqres Api

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Step 1 Check version Newman and Node
        run: |
          newman --version
          node --version

      - name: Step 2 Install Newman-Reporter-Htmlextra
        run: npm install -g newman-reporter-htmlextra

      - name: Step 3 Execute collection
        run: newman run ./reqres-api.json --reporters cli,htmlextra --reporter-htmlextra-export ./results/Report.html

      - name: Step 4 Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: ./results/Report.html

      - name: Step 5 Create report link
        id: create_report_link
        run: |
          echo "::set-output name=url::$(echo ${{ github.server_url }}/${{ github.repository }}/${{ github.run_id }}/artifacts/download/report/Report.html)"

      - name: Step 6 Comment with report link
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const reportLink = context.outputs.create_report_link;
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `View the HTML report: [Report](${reportLink})`
            })
