name: Postman Teste reqres Api

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Step 1 Check version Newman and Node
        run: |
          newman --version
          node --version

      - name: Step 2 Install Newman-Reporter-Allure
        run: sudo npm install -g newman-reporter-allure
        
      - name: Step 4 Archive Allure results
        uses: actions/upload-artifact@v2
        with:
          name: allure-results
          path: ./allure-results

      - name: Download and Install Allure CLI
        run: |
          wget https://github.com/allure-framework/allure2/releases/latest/download/allure-2.22.4.zip
          unzip allure-2.22.4.zip -d allure
          sudo ln -s allure/allure-2.22.4/bin/allure /usr/bin/allure
          export PATH="/usr/bin/allure:$PATH"

      - name: Step 3 Execute collection
        run: newman run ./reqres-api.json -r allure --reporter-allure-export ./allure-results

      - name: Download and Install Allure CLI
        run: |
          wget https://github.com/allure-framework/allure2/releases/latest/download/allure-2.22.4.zip
          unzip allure-2.22.4.zip -d allure
          sudo ln -s allure/allure-2.22.4/bin/allure /usr/bin/allure
          export PATH="/usr/bin/allure:$PATH"

      - name: Step 5 Generate Allure Report
        run: |
          allure generate ./allure-results -o ./allure-report
          echo "ALLURE_REPORT_PATH=$(realpath ./allure-report)" >> $GITHUB_ENV

      - name: Archive Allure Report
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: ./allure-report
