name: Postman Allure Report

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Newman and Allure Command Line
        run: |
          npm install -g newman
          npm install -g allure-commandline

      - name: Execute Postman collection
        run: newman run ./reqres-api.json --reporters allure

      - name: Generate Allure Report
        run: allure generate -c -o ./allure-report

      - name: Archive Allure Report
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: ./allure-report

      - name: Set Allure Report URL
        run: echo "ALLURE_REPORT_URL=https://github.com/$GITHUB_REPOSITORY/actions/artifacts/$GITHUB_RUN_ID" >> $GITHUB_ENV
